package view;

import model.Pelicula;
import model.PeliculaDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Rai
 */
public class FormListarPeliculas extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormListarPeliculas.class.getName());
    private PeliculaDAO dao = new PeliculaDAO();

    /**
     * Creates new form FormListarPeliculas
     */
    public FormListarPeliculas() {
        initComponents();
        cargarTabla(dao.listarTodas());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFiltroGenero = new javax.swing.JLabel();
        cmbGeneroFiltro = new javax.swing.JComboBox<>();
        btnFiltrarGenero = new javax.swing.JButton();
        lblAnioInicio = new javax.swing.JLabel();
        lblAnioFin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAnioInicio = new javax.swing.JTextField();
        txtAnioFin = new javax.swing.JTextField();
        btnFiltrarRango = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCartelera = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFiltroGenero.setText("Buscar por Genero");

        cmbGeneroFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comedia", "Drama", "Acción", "Terror", "Ciencia Ficción", "Animación" }));
        cmbGeneroFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGeneroFiltroActionPerformed(evt);
            }
        });

        btnFiltrarGenero.setText("Filtrar por Genero");
        btnFiltrarGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarGeneroActionPerformed(evt);
            }
        });

        lblAnioInicio.setText("Desde");

        lblAnioFin.setText("Hasta");

        jLabel3.setText("Año Pelicula");

        btnFiltrarRango.setText("Filtrar por Año");
        btnFiltrarRango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarRangoActionPerformed(evt);
            }
        });

        jTableCartelera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableCartelera);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFiltroGenero)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbGeneroFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblAnioFin)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtAnioFin, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnFiltrarRango)
                                    .addComponent(btnFiltrarGenero)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAnioInicio)
                                .addGap(18, 18, 18)
                                .addComponent(txtAnioInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFiltroGenero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbGeneroFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltrarGenero))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnioInicio)
                    .addComponent(txtAnioInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnioFin)
                    .addComponent(txtAnioFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltrarRango))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarTabla(List<Pelicula> lista) {
        // Define el modelo y las columnas
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new Object[]{"ID", "Titulo", "Director", "Anio", "Duracion", "Genero"});

        // Llenar el modelo con los datos de la lista
        for (Pelicula p : lista) {
            modelo.addRow(new Object[]{
                p.getId(),
                p.getTitulo(),
                p.getDirector(),
                p.getAnio(),
                p.getDuracion(),
                p.getGenero()
            });
        }
        jTableCartelera.setModel(modelo);
    }


    private void cmbGeneroFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGeneroFiltroActionPerformed

    }//GEN-LAST:event_cmbGeneroFiltroActionPerformed

    private void btnFiltrarRangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarRangoActionPerformed
        try {
            int inicio = Integer.parseInt(txtAnioInicio.getText());
            int fin = Integer.parseInt(txtAnioFin.getText());

            if (inicio > fin) {
                JOptionPane.showMessageDialog(this, "El anio de inicio debe ser menor o igual al anio de fin.");
                return;
            }

            List<Pelicula> listaFiltrada = dao.listarPorRangoAnios(inicio, fin);
            cargarTabla(listaFiltrada);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese numeros validos para el rango de anios.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnFiltrarRangoActionPerformed

    private void btnFiltrarGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarGeneroActionPerformed
        String generoSeleccionado = (String) cmbGeneroFiltro.getSelectedItem();
        if (generoSeleccionado != null && !generoSeleccionado.isEmpty()) {
            List<Pelicula> listaFiltrada = dao.listarPorGenero(generoSeleccionado);
            cargarTabla(listaFiltrada);
        }
    }//GEN-LAST:event_btnFiltrarGeneroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormListarPeliculas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrarGenero;
    private javax.swing.JButton btnFiltrarRango;
    private javax.swing.JComboBox<String> cmbGeneroFiltro;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCartelera;
    private javax.swing.JLabel lblAnioFin;
    private javax.swing.JLabel lblAnioInicio;
    private javax.swing.JLabel lblFiltroGenero;
    private javax.swing.JTextField txtAnioFin;
    private javax.swing.JTextField txtAnioInicio;
    // End of variables declaration//GEN-END:variables
}
